theme = "catppuccin"
hide-cursor-when-typing = true
padding-x = 15
padding-y = [0, 0]
option-as-alt = 'both'         # 'both', 'left' and 'right'
line-height = 1.0
confirm-before-quit = false
# working-dir = "/Users/raphael/Documents/"

[cursor]
shape = 'beam'          # 'block', 'underline', 'beam' or 'hidden'
blinking = false
blinking-interval = 800

[editor]
program = "/opt/homebrew/bin/nvim"
# args = []

[window]
mode = "Maximized"          # "Windowed", "Maximized" or "Fullscreen"
opacity = 1.0
blur = false
decorations = "Transparent" #  "Enabled", "Disabled", "Transparent", "Buttonless"

[fonts]
size = 18
family = "Hasklug Nerd Font Mono"

[bindings]
keys = [
  { key = "/", with = "super", action = "SplitRight" },
  { key = "\\", with = "super", action = "SplitDown" },
]

# Renderer
#
# • Performance: Set WGPU rendering performance
#   - High: Adapter that has the highest performance. This is often a discrete GPU.
#   - Low: Adapter that uses the least possible power. This is often an integrated GPU.
#
# • Backend: Set WGPU rendering backend
#   - Automatic: Leave Sugarloaf/WGPU to decide
#   - GL: Supported on Linux/Android, and Windows and macOS/iOS via ANGLE
#   - Vulkan: Supported on Windows, Linux/Android
#   - DX12: Supported on Windows 10
#   - Metal: Supported on macOS/iOS
#
# • disable-unfocused-render: This property disable renderer processes while Rio is unfocused.
#
# • level: Configure renderer level
#   - Available options: 0 and 1.
#       Higher the level more rendering features and computations
#       will be done like enable font ligatures or emoji support.
#       For more information please check the docs.
#
# • filters: A list of paths to RetroArch slang shaders. Might not work with OpenGL.
#
# Example:
# [renderer]
# performance = "high"
# backend = "automatic"
# disable-unfocused-render = false
# level = 1
# filters = []

# Keyboard
#
# use-kitty-keyboard-protocol - Enable Kitty Keyboard protocol
#
# disable-ctlseqs-alt - Disable ctlseqs with ALT keys
#   - For example: Terminal.app does not deal with ctlseqs with ALT keys
#
# Example:
# [keyboard]
# use-kitty-keyboard-protocol = false
# disable-ctlseqs-alt = false

# [scroll]
# multiplier = 3.0
# divider = 1.0

# Navigation
#
# "mode" - Define navigation mode
#   • NativeTab (MacOS only)
#   • Bookmark
#   • BottomTab
#   • TopTab
#   • Plain
#
# "hide-if-single" - Hide navigation UI if is single.
# "clickable" - Enable click on tabs to switch.
# "use-current-path" - Use same path whenever a new tab is created (Note: requires `use-fork` to be set to false).
# "color-automation" - Set a specific color for the tab whenever a specific program is running, or in a specific directory.
#
# Example:
# [navigation]
# mode = "Bookmark"
# clickable = false
# hide-if-single = true
# use-current-path = false
# color-automation = []

# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["new-session", "-c", "/var/www"]
