#!/usr/bin/env zsh
# [MISE] description="pls list show hidden files"
# [USAGE] arg "<file>"
# [MISE] dir="{{cwd}}"

quarto render "$usage_file" --to revealjs --output-dir "$HOME/Documents/Presentations"
