# tldr --show-paths

[display]
compact = false
use_pager = false

# style attributes
#   foreground (color string, ANSI code, or RGB)
#   background (color string, ANSI code, or RGB)
#   underline (true or false)
#   bold (true or false)
#   italic (true or false)

# catppuccin colors
#   rosewater: { rgb = { r = 244, g = 224, b = 220 } } # rosewater
#   flamingo: { rgb = { r = 242, g = 205, b = 205 } } # flamingo
#   pink: { rgb = { r = 245, g = 194, b = 231 } } # pink
#   mauve: { rgb = { r = 203, g = 166, b = 247 } } # mauve
#   red: { rgb = { r = 243, g = 139, b = 168 } } # red
#   maroon: { rgb = { r = 235, g = 160, b = 173 } } # maroon
#   peach: { rgb = { r = 250, g = 179, b = 135 } } # peach
#   yellow: { rgb = { r = 249, g = 226, b = 175 } } # yellow
#   green: { rgb = { r = 166, g = 227, b = 161 } } # green
#   teal: { rgb = { r = 147, g = 226, b = 213 } } # teal
#   sky: { rgb = { r = 137, g = 220, b = 235 } } # sky
#   sapphire: { rgb = { r = 116, g = 199, b = 236 } } # sapphire
#   blue: { rgb = { r =  137, g = 180, b = 250 } } # blue
#   lavender: { rgb = { r = 180, g = 190, b = 254 } } # lavender
#   text: { rgb = { r = 205, g = 214, b = 244 } } # text

[style.description]
foreground = { rgb = { r = 166, g = 227, b = 161 } } # green

[style.command_name]
foreground = { rgb = { r = 250, g = 179, b = 135 } } # peach

[style.example_text]
foreground = { rgb = { r = 137, g = 180, b = 250 } } # blue

[style.example_code]
foreground = { rgb = { r = 180, g = 190, b = 254 } } # lavender 

[style.example_variable]
foreground = { rgb = { r = 137, g = 220, b = 235 } } # sky
underline = false

[updates]
auto_update = true

# [directories]
# cache_dir = "/home/myuser/.tealdeer-cache/"
# custom_pages_dir = "/home/myuser/custom-tldr-pages/"
