"$schema" = 'https://starship.rs/config-schema.json'

###########  CONFIG  #############

add_newline = true
command_timeout = 5000

###########  SEGMENTS  #############

format = """

$line_break\


[](fg:color_shell)\
${custom.shicon}\
$jobs\
[ ](bg:color_shell fg:color_shell_text)\
[](fg:color_shell bg:color_directory)\
$directory\
[](fg:color_directory bg:color_lang)\
$nodejs\
$deno\
$golang\
$python\
$lua\
$rust\
$zig\
[](fg:color_lang bg:color_git)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:color_git bg:color_direnv)\
${custom.direnv}\
[](fg:color_direnv)\
$fill\
$character\
$cmd_duration\

$line_break\
$username\
$shlvl\


$buf\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$crystal\
$sudo\
$status\
$container\
"""


# $vlang
# $vagrant
# $typst
# $pulumi
# $fennel
# $package
# $docker_context
# $kubernetes
# $localip
# $hostname
# $env_var
# $battery
# $os
# $time

###########  COLORS  #############

palette = 'custom'
[palettes.custom]
color_shell = '#da6871'          # red - choosen using oklch
color_shell_text = '#251415'     # black 92% opacity
color_directory = '#22c5c7'      # green - choosen using oklch
color_directory_text = '#112424' # black 92% opacity
color_lang = '#3a9ef4'           # blue - choosen using oklch
color_lang_text = '#101d2c'      # black 92% opacity
color_git = '#fef1b9'            # yellow - adjusted
color_git_text = '#2f2d23'       # black 92% opacity
color_time = '#da6871'           # red - choosen using oklch
color_time_text = '#251415'      # black 92% opacity
color_direnv = '#d1a3fd'          # green - choosen using oklch
color_direnv_text = '#261f2f'     # black 92% opacity

############  SEGMENT SPECS  ############



[username]
format = '[$user ]($style)'

# prompt
[shlvl]
disabled = false
style = "fg:color_shell bg:color_shell_text"
format = "[$symbol ]($style)"
repeat = true
symbol = "❯"
repeat_offset = 0
threshold = 0

[custom.shicon]
command = "~/.config/starship/shicon"
when = true
style = "bg:color_shell fg:color_shell_text"
format =  "[$output]($style)"

[jobs]
symbol = '+'
number_threshold = 1
symbol_threshold = 1
style = "bg:color_time fg:color_time_text"
format = '[$symbol$number]($style)'

[directory]
style = "bg:color_directory fg:color_directory_text"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = ""
home_symbol = ""

[golang]
symbol = "go"
style = "bg:color_lang fg:color_lang_text"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ""
style = "bg:color_lang fg:color_lang_text"
format = '[ $symbol ($version) ]($style)'

[zig]
symbol = ""
style = "bg:color_lang fg:color_lang_text"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:color_lang fg:color_lang_text"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""                               #  
style = "bg:color_lang fg:color_lang_text"
format = '[ $symbol ($version) ]($style)'
detect_extensions = []

[deno]
symbol = "┓"
style = "bg:color_lang fg:color_lang_text"
format = '[ $symbol ($version) ]($style)'
detect_files = ["deno.json"]

[python]
symbol = ""
style = "bg:color_lang fg:color_lang_text"
format = '[ $symbol ($version )($virtualenv )]($style)'

[git_branch]
symbol = ""
style = "bg:color_git fg:color_git_text"
format = '[ $symbol$branch ]($style)'

[git_commit]
style = "bg:color_git fg:color_git_text"
format = '[\($hash$tag\) ]($style)'
tag_disabled = false

[git_state]
style = "bg:color_git fg:color_git_text"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "bg:color_git fg:color_git_text"
deleted_style = "bg:235 fg:bright-red"
disabled = true

[git_status]
behind = ""
ahead = ""
style = "bg:color_git fg:color_git_text"
format = '[$all_status$ahead_behind ]($style)'

[custom.direnv]
command = "~/.config/starship/envicon"
when = "~/.config/starship/envwhen"
style = "bg:color_direnv fg:color_direnv_text"
format = "[ $output ]($style)"

[fill]
symbol = ' '

[cmd_duration]
style = "fg:bright-white"
format = "[ $duration]($style)"

[character]
success_symbol = ''
error_symbol = '[ ✗‼](#da6871) '

[time]
disabled = false
time_format = "%R"                         # Hour:Minute Format
style = "bg:color_time fg:color_time_text"
format = '[$time]($style)'




