[tools]
node = "latest"
git = "latest"
python = "latest"
bun = "latest"
pipx = "latest"
deno = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"

[settings]
experimental = true
python_compile = false
