[tools]
git = "latest"
bun = "latest"
deno = "latest"
uv = "latest"
python = "latest"
node = "latest"
go = "latest"

[settings]
experimental = true
python_compile = false
idiomatic_version_file_enable_tools = []
