[tools]
bun = "latest"
deno = "latest"
uv = "latest"
node = "latest"
go = "latest"
git = "latest"
"cargo:sbyte" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
python = "latest"
"npm:nuekit" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"

[settings]
experimental = true
python_compile = false
idiomatic_version_file_enable_tools = []
