[tools]
node = "latest"
git = "latest"
python = "latest"
bun = "latest"
pipx = "latest"
deno = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
"go:honnef.co/go/tools/cmd/structlayout" = "latest"
"go:honnef.co/go/tools/cmd/structlayout-optimize" = "latest"
"go:honnef.co/go/tools/cmd/structlayout-pretty" = "latest"

[settings]
experimental = true
python_compile = false
