[tools]
bun = "latest"
deno = "latest"
uv = "latest"
node = "latest"
go = "latest"
git = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
"cargo:sbyte" = "latest"
"cargo:cargo-update" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:nuekit" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"pipx:ruff" = "latest"
"go:github.com/dimonomid/nerdlog/cmd/nerdlog" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
"go:github.com/wailsapp/wails/v2/cmd/wails" = "latest"
"go:github.com/danielmiessler/fabric" = "latest"

[settings]
experimental = true
python_compile = false
idiomatic_version_file_enable_tools = []
