[tools]
"npm:md-to-pdf" = "latest"
"npm:github-markdown-css" = "latest"
"github:h0rv/d2-mcp" = "latest"
"npm:@mixedbread/mgrep" = "latest"
"github:jdx/fnox" = "latest"
"github:sharkdp/fd" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:sharkdp/pastel" = "latest"
"github:neilotoole/sq" = "latest"
"github:sxyazi/yazi" = "latest"
"github:ajeetdsouza/zoxide" = "latest"
"github:o2sh/onefetch" = "latest"
"github:Slackadays/Clipboard" = "latest"
"github:bee-san/RustScan" = "latest"
"npm:skills" = "latest"
claude-code = "latest"

[settings]
experimental = true
quiet = true
