column_width = 120
line_endings = "Unix" # Windows, Unix
indent_type = "Spaces" # Spaces, Tabs
indent_width = 2
quote_style = "AutoPreferSingle" # AutoPreferSingle, AutoPreferDouble, ForceSingle, ForceDouble
call_parentheses = "Always" # Always, NoSingleString, NoSingleTable, NoParentheses, Inout, None
collapse_simple_statement = "Always" # Always, Never, FunctionOnly, ConditionalOnly

[sort_requires]
enabled = true