#!/usr/bin/env zsh
# [MISE] description="Google antigravity editor"
# [MISE] dir="{{cwd}}"

if [ $# -gt 0 ]; then
  print -P "%F{magenta}agy $@ %f"
  print
  agy "$@"
else
  print -P "%F{magenta}agy . %f"
  print
  agy .
fi
