#!/usr/bin/env zsh
# [MISE] description="Cursor editor"
# [MISE] dir="{{cwd}}"

if [ $# -gt 0 ]; then
  print -P "%F{magenta}cursor $@ %f"
  print
  cursor "$@"
else
  print -P "%F{magenta}cursor . %f"
  print
  cursor .
fi
