#!/usr/bin/env zsh
# [MISE] description="fresh editor"
# [MISE] dir="{{cwd}}"

if [ $# -gt 0 ]; then
  print -P "%F{magenta}fresh $@ %f"
  print
  fresh "$@"
else
  print -P "%F{magenta}fresh . %f"
  print
  fresh .
fi
