#!/usr/bin/env zsh
# [MISE] description="Micro editor"
# [MISE] dir="{{cwd}}"

if [ $# -gt 0 ]; then
  print -P "%F{magenta}micro $@ %f"
  print
  micro "$@"
else
  print -P "%F{magenta}micro . %f"
  print
  micro .
fi
