#!/usr/bin/env zsh
# [MISE] description="Neovim editor"
# [MISE] dir="{{cwd}}"

if [ $# -gt 0 ]; then
  print -P "%F{magenta}nvim $@ %f"
  print
  nvim "$@"
else
  print -P "%F{magenta}nvim . %f"
  print
  nvim .
fi
