#!/usr/bin/env zsh
# [MISE] description="vscode editor"
# [MISE] dir="{{cwd}}"

if [ $# -gt 0 ]; then
  print -P "%F{magenta}code $@ %f"
  print
  code "$@"
else
  print -P "%F{magenta}code . %f"
  print
  code .
fi
