#!/usr/bin/env zsh
# [MISE] description="zed editor"
# [MISE] dir="{{cwd}}"

# zed editor

if [ $# -gt 0 ]; then
  print -P "%F{magenta}zed $@ %f"
  print
  zed "$@"
else
  print -P "%F{magenta}zed . %f"
  print
  zed .
fi
