#!/usr/bin/env zsh
# [MISE] description="Zed editor"
# [MISE] dir="{{cwd}}"

if [ $# -gt 0 ]; then
  print -P "%F{magenta}zed $@ %f"
  print
  zed "$@"
else
  print -P "%F{magenta}zed . %f"
  print
  zed .
fi
