# rosewater = { rgb = [244, 224, 220] }
# flamingo = { rgb = [242, 205, 205] }
# pink = { rgb = [245, 194, 231] }
# mauve = { rgb = [203, 166, 247] }
# red = { rgb = [243, 139, 168] }
# maroon = { rgb = [235, 160, 173] }
# peach = { rgb = [250, 179, 135] }
# yellow = { rgb = [249, 226, 175] }
# green = { rgb = [166, 227, 161] }
# teal = { rgb = [147, 226, 213] }
# sky = { rgb = [137, 220, 235] }
# sapphire = { rgb = [116, 199, 236] }
# blue = { rgb = [137, 180, 250] }
# lavender = { rgb = [180, 190, 254] }
# text = { rgb = [205, 214, 244] }


[cache]
dir = "/Users/ken/Library/Caches/tlrc"
mirror = "https://github.com/tldr-pages/tldr/releases/latest/download"
auto_update = true
max_age = 336
languages = []

[output]
show_title = true
platform_title = false
show_hyphens = false
example_prefix = "- "
compact = false
raw_markdown = false

[indent]
title = 2
description = 2
bullet = 2
example = 4

[style.title]
color = { rgb = [250, 179, 135] }
background = "default"
bold = true
underline = false
italic = false
dim = false
strikethrough = false

[style.description]
color = { rgb = [250, 179, 135] }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.bullet]
color = { rgb = [166, 227, 161] }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.example]
color = { rgb = [147, 226, 213] }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.url]
color = { rgb = [243, 139, 168] }
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.inline_code]
color = { rgb = [249, 226, 175] }
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.placeholder]
color = { rgb = [243, 139, 168] }
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false
