# see github mcp registry: https://github.com/mcp
[mcp]

# markitdown - 82,000 github mcp downloads
[mcp.markitdown]
type = "stdio"
command = ["uvx", "--python", "3.13", "--prerelease", "allow", "markitdown-mcp"]

# npmjs - 35,000 github mcp downloads
[mcp.context7]
command = ["bunx", "@upstash/context7-mcp"]

# github - 24,000 github mcp downloads
[mcp.github]
type = "remote"
url = "https://api.githubcopilot.com/mcp"
headers = { Authorization = "Bearer $GITHUB_PERSONAL_ACCESS_TOKEN" }

# playwright - 22,000 github mcp downloads
[mcp.playwright]
command = ["bunx", "@playwright/mcp@latest"]
env = { OPENAI_API_KEY = "$OPENAI_API_KEY" }

[mcp.lint]
type = "stdio"
command = ["$BINPATH/mcp_biome"]

[mcp.chrome-devtools]
type = "stdio"
command = ["bunx", "chrome-devtools-mcp@latest"]

[mcp.linear]
type = "stdio"
command = ["bunx", "mcp-remote", "https://mcp.linear.app/sse"]

[mcp.seagoat]
type = "stdio"
command = ["$BINPATH/mcp_seagoat"]

[mcp.tokei]
type = "stdio"
command = ["$BINPATH/mcp_tokei"]

# npmjs - 13000 weekly downloads
[mcp.n8n-mcp]
command = ["bunx", "n8n-mcp"]
env = { MCP_MODE = "stdio", LOG_LEVEL = "error", DISABLE_CONSOLE_OUTPUT = "true" }

# npmjs - 3000 weekly downloads
[mcp.mcp-server-chart]
command = ["bunx", "@antv/mcp-server-chart"]

# npmjs - 750 weekly downloads
[mcp.Obsidian]
command = ["bunx", "mcp-obsidian", "$OBSIDIAN_VAULT"]

# github
[mcp.serena]
type = "stdio"
command = [
    "uvx",
    "--from",
    "git+https://github.com/oraios/serena",
    "serena",
    "start-mcp-server",
    "--context",
    "ide-assistant",
    "--project",
    "$PWD",
]

# redundant in claude and opencode

# [mcp.sequential-thinking]
# command = ["bunx", "@modelcontextprotocol/server-sequential-thinking"]

# [mcp.memory]
# command = ["bunx", "@modelcontextprotocol/server-memory"]

# [mcp.filesystem]
# command = ["bunx", "@modelcontextprotocol/server-filesystem"]
