#!/usr/bin/env bash
# [MISE] description="Rosetta on|off"

state="${1:-}"

if [[ "$state" == "on" ]]; then
  echo "Installing Rosetta (requires sudo)..."
  sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license 2>/dev/null
  echo
  pkgutil --pkg-info com.apple.pkg.RosettaUpdateAuto
elif [[ "$state" == "off" ]]; then
  echo "Rosetta files are now protected by System Integrity Protection (SIP)."
else
  arch -x86_64 /usr/bin/true 2>/dev/null && echo "Rosetta is installed" || echo "Rosetta is not installed"
fi
