#!/usr/bin/env zsh
# [MISE] description="Create a symlink named symlink-<filename>"
# [MISE] dir="{{cwd}}"

if [[ -z "$1" ]]; then
  echo "Usage: symlink <file>"
  exit 1
fi

if [[ ! -e "$1" ]]; then
  echo "Error: '$1' does not exist"
  exit 1
fi

original_abs=$(realpath "$1")
filename=$(basename "$original_abs")
dir=$(dirname "$original_abs")

symlink_name="symlink-${filename}"
symlink_path="${dir}/${symlink_name}"

ln -s "$original_abs" "$symlink_path"
echo "$symlink_name -> $filename"
