#!/usr/bin/env bash

# active_color="gradient(top_left=0xff00ff00,bottom_right=0x00000000)"
# active_color="0xff00ff00"
options=(
  style=uniform
  width=5.0
  hidpi=on
  active_color="0xff00ff00"
  inactive_color=0x00000000
  ax_focus=off
  blacklist="DeskMinder,Dock"
)

borders "${options[@]}"
