#!/usr/bin/env bash

# active_color="gradient(top_left=0xff00ff00,bottom_right=0x00000000)"
# active_color="0xff00ff00"
options=(
  style=round
  width=5.0
  hidpi=off
  active_color="0xff00ff00"
  inactive_color=0x00000000
)

borders "${options[@]}"

blacklist="DeskMinder,com.appps.NewDesk"
