[mcp]

[mcp.lint]
type = "stdio"
command = ["$BINPATH/mcp_biome"]

[mcp.chrome-devtools]
type = "stdio"
command = ["bunx", "chrome-devtools-mcp@latest"]

[mcp.linear]
type = "stdio"
command = ["bunx", "mcp-remote", "https://mcp.linear.app/sse"]

[mcp.seagoat]
type = "stdio"
command = ["$BINPATH/mcp_seagoat"]

[mcp.tokei]
type = "stdio"
command = ["$BINPATH/mcp_tokei"]

# npmjs - 350,000 weekly downloads
[mcp.playwright]
command = ["bunx", "@playwright/mcp@latest"]
env = { OPENAI_API_KEY = "$OPENAI_API_KEY" }

# npmjs - 273,000 downloads/month
[mcp.context7]
command = ["bunx", "@upstash/context7-mcp"]

# npmjs - 196,000 downloads/month
[mcp.filesystem]
command = ["bunx", "@modelcontextprotocol/server-filesystem"]

# npmjs - 91,000 downloads/month
[mcp.sequential-thinking]
command = ["bunx", "@modelcontextprotocol/server-sequential-thinking"]

# npmjs - 65,000 weekly downloads
[mcp.memory]
command = ["bunx", "@modelcontextprotocol/server-memory"]

# npmjs - 13000 weekly downloads
[mcp.n8n-mcp]
command = ["bunx", "n8n-mcp"]
env = { MCP_MODE = "stdio", LOG_LEVEL = "error", DISABLE_CONSOLE_OUTPUT = "true" }

# npmjs - 3000 weekly downloads
[mcp.mcp-server-chart]
command = ["bunx", "@antv/mcp-server-chart"]

# npmjs - 1200 weekly downloads
[mcp.spec-workflow]
command = ["bunx", "@pimzino/spec-workflow-mcp@latest", "$PWD"]

# npmjs - 750 weekly downloads
[mcp.Obsidian]
command = ["bunx", "mcp-obsidian", "$OBSIDIAN_VAULT"]

# github
[mcp.serena]
type = "stdio"
command = ["uvx", "--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "ide-assistant", "--project", "$PWD"]

[mcp.github]
command = ["docker", "run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server"]
env = { GITHUB_PERSONAL_ACCESS_TOKEN = "$GITHUB_PERSONAL_ACCESS_TOKEN" }

