[mcp.Obsidian]
command = ["bunx", "mcp-obsidian", "/Users/ken/Documents/obsidian/Vault"]

[mcp.context7]
command = ["bunx", "@upstash/context7-mcp"]

[mcp.mcp-sequentialthinking-tools]
command = ["bunx", "mcp-sequentialthinking-tools"]
env = { MAX_HISTORY_SIZE = "1000" }

[mcp.github]
command = ["docker", "run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server"]

[mcp.playwright]
command = ["bunx", "@playwright/mcp@latest"]

[mcp.mcp-server-chart]
command = ["bunx", "@antv/mcp-server-chart"]

[mcp.taskmaster-ai]
command = ["bunx", "--package=task-master-ai", "task-master-ai"]

[mcp.spec-workflow]
command = ["bunx", "@pimzino/spec-workflow-mcp@latest"]
