# Platform definitions
[platform.claude]
name = "Claude Code"
config-file = ".mcp.json"
permissions-file = ".claude/settings.local.json"

[platform.opencode]
name = "OpenCode"
config-file = "opencode.json"
permissions-file = "opencode.json"

# Tool definitions
[tool.github-spec-kit]
name = "GitHub Spec-kit"
description = "Initialize spec-kit with AI support"

[tool.github-spec-kit.install]
command = "uvx --from git+https://github.com/github/spec-kit.git specify init --here --ai claude"
stdin = "y\n"
env = ["PYTHONUNBUFFERED=1"]
initial-message = "🔄 Initializing spec-kit...\n\nThis may take a few minutes as dependencies are downloaded and configured.\n\n"
success-message = "✅ Spec-kit initialized successfully!"
detect-path = ".specify"
uninstall-paths = [".specify", ".claude/commands/speckit*", ".claude/commands/specify.md", ".claude/commands/clarify.md", ".claude/commands/plan.md", ".claude/commands/tasks.md", ".claude/commands/analyze.md", ".claude/commands/implement.md", ".claude/commands/constitution.md"]

[tool.openspec]
name = "OpenSpec"
description = "Initialize OpenSpec with AI support"

[tool.openspec.install]
command = "bunx @fission-ai/openspec@latest init --tools claude"
env = ["NODE_ENV=production"]
initial-message = "🔄 Initializing OpenSpec...\n\nThis may take a few minutes as dependencies are downloaded and configured.\n\n"
success-message = "✅ OpenSpec initialized successfully!"
detect-path = "openspec"
uninstall-paths = ["openspec", ".claude/commands/openspec"]

[tool.full-permission]
name = "Full Permission"
description = "Enable all Claude Code tool permissions"

[tool.full-permission.claude]
permissions = { tools = ["Bash", "Read", "Edit", "Write", "WebFetch", "Grep", "Glob", "LS", "MultiEdit", "NotebookRead", "NotebookEdit", "TodoRead", "TodoWrite", "WebSearch"], level = "allow" }

[tool.full-permission.opencode]
permissions = { tools = ["bash", "read", "edit", "write"], level = "allow" }

# UI configuration
[ui]
tabs = ["Tools", "MCP"]
