# Platform definitions
[platform.claude]
name = "Claude Code"
config-file = ".mcp.json"
permissions-file = ".claude/settings.local.json"

[platform.opencode]
name = "OpenCode"
config-file = "opencode.json"
permissions-file = "opencode.json"

# Tool definitions
[tool.github-spec-kit]
name = "GitHub Spec-kit"
description = "Initialize spec-kit with AI support"

[tool.github-spec-kit.install]
command = "uvx --from git+https://github.com/github/spec-kit.git specify init --here --ai claude"
stdin = "y\n"
env = ["PYTHONUNBUFFERED=1"]
initial-message = "🔄 Initializing spec-kit...\n\nThis may take a few minutes as dependencies are downloaded and configured.\n\n"
success-message = "✅ Spec-kit initialized successfully!"
detect-path = ".specify"
uninstall-paths = [".specify", ".claude/commands/speckit*", ".claude/commands/specify.md", ".claude/commands/clarify.md", ".claude/commands/plan.md", ".claude/commands/tasks.md", ".claude/commands/analyze.md", ".claude/commands/implement.md", ".claude/commands/constitution.md"]

[tool.openspec]
name = "OpenSpec"
description = "Initialize OpenSpec with AI support"

[tool.openspec.install.claude]
command = "bunx @fission-ai/openspec@latest init --tools claude"
env = ["NODE_ENV=production"]
initial-message = "🔄 Initializing OpenSpec...\n\nThis may take a few minutes as dependencies are downloaded and configured.\n\n"
success-message = "✅ OpenSpec initialized successfully!"
detect-path = "openspec"
uninstall-paths = ["openspec", ".claude/commands/openspec*", "AGENTS.md", "CLAUDE.md"]

[tool.openspec.install.opencode]
command = "bunx @fission-ai/openspec@latest init --tools opencode"
env = ["NODE_ENV=production"]
initial-message = "🔄 Initializing OpenSpec...\n\nThis may take a few minutes as dependencies are downloaded and configured.\n\n"
success-message = "✅ OpenSpec initialized successfully!"
detect-path = "openspec"
uninstall-paths = ["openspec", ".opencode/command/openspec*", "AGENTS.md"]

[tool.full-permission]
name = "Full Permission"
description = "Enable all tool permissions"

[tool.full-permission.install.claude]
installer = "merge"
source-file = "configs/claude/permissions/full-permission.json"
target-file = ".claude/settings.local.json"
initial-message = "🔄 Configuring Claude permissions..."
success-message = "✅ Claude permissions configured!"
detect-path = ".claude/settings.local.json"

[tool.full-permission.install.opencode]
installer = "merge"
source-file = "configs/opencode/permissions/full-permission.json"
target-file = "opencode.json"
initial-message = "🔄 Configuring OpenCode permissions..."
success-message = "✅ OpenCode permissions configured!"
detect-path = "opencode.json"

# UI configuration
[ui]
tabs = ["Tools", "MCP"]
