# Platform definitions
[platform.claude]
name = "Claude Code"
config-file = ".mcp.json"
permissions-file = ".claude/settings.local.json"

[platform.opencode]
name = "OpenCode"
config-file = "opencode.json"
permissions-file = "opencode.json"

# Tool definitions
[tool.github-spec-kit]
name = "GitHub Spec-kit"
description = "Initialize spec-kit with AI support"
platform-agnostic = true
has-install = true
install-command = "uvx --from git+https://github.com/github/spec-kit.git specify init --here --ai claude"
install-stdin = "y\n"
install-env = ["PYTHONUNBUFFERED=1"]
install-initial-message = "🔄 Initializing spec-kit...\n\nThis may take a few minutes as dependencies are downloaded and configured.\n\n"
install-success-message = "✅ Spec-kit initialized successfully!"
uninstall-paths = [".specify", ".claude/commands/speckit*", ".claude/commands/specify.md", ".claude/commands/clarify.md", ".claude/commands/plan.md", ".claude/commands/tasks.md", ".claude/commands/analyze.md", ".claude/commands/implement.md", ".claude/commands/constitution.md"]
detect-path = ".specify"

[tool.openspec]
name = "OpenSpec"
description = "Initialize OpenSpec with AI support"
platform-agnostic = true
has-install = true
install-command = "bunx @fission-ai/openspec@latest init --tools claude"
install-env = ["NODE_ENV=production"]
install-initial-message = "🔄 Initializing OpenSpec...\n\nThis may take a few minutes as dependencies are downloaded and configured.\n\n"
install-success-message = "✅ OpenSpec initialized successfully!"
uninstall-paths = ["openspec", ".claude/commands/openspec"]
detect-path = "openspec"

[tool.full-permission]
name = "Full Permission"
description = "Enable all Claude Code tool permissions"
platform-agnostic = false
has-install = true

[tool.full-permission.permissions.claude]
tools = ["Bash", "Read", "Edit", "Write", "WebFetch", "Grep", "Glob", "LS", "MultiEdit", "NotebookRead", "NotebookEdit", "TodoRead", "TodoWrite", "WebSearch"]
level = "allow"

[tool.full-permission.permissions.opencode]
tools = ["bash", "read", "edit", "write"]
level = "allow"

# UI configuration
[ui]
tabs = ["Tools", "MCP"]
