# "$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 4
final_space = true

[palette]
directory = '#2f40c2'
directory-foreground = '#e5e6f2'
language = '#005b95'
language-foreground = '#e5eaf0'
git = '#006b1d'
git-foreground = '#e5ece6'
git-modified = '#a17a00'
git-diverged = '#8c0888'
git-ahead = '#8c0888'
git-behind = '#8c0888'
model = '#005b95'
model-foreground = '#e5eaf0'
context-green = '#006b1d'
context-yellow = '#a17a00'
context-orange = '#f55c1b'
context-foreground = '#e5e6f2'


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

######### CLAUDE MODEL #########

[[blocks.segments]]
type = "claude"
style = "diamond"
leading_diamond = ''
trailing_diamond = ''
background = 'p:model'
foreground = 'p:model-foreground'
template = " {{ .Model.DisplayName }} "

######### CLAUDE CONTEXT #########

[[blocks.segments]]
type = "claude"
style = "diamond"
leading_diamond = ''
trailing_diamond = ''
background = 'p:context-green'
foreground = 'p:context-foreground'
template = " {{ .TokenUsagePercent.String }}% "
background_templates = [
  '{{ if lt .TokenUsagePercent.Value 50.0 }}p:context-green{{ end }}',
  '{{ if and (ge .TokenUsagePercent.Value 50.0) (lt .TokenUsagePercent.Value 75.0) }}p:context-yellow{{ end }}',
  '{{ if ge .TokenUsagePercent.Value 75.0 }}p:context-orange{{ end }}',
]
