# "$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 4
final_space = true
# streaming = 100

[palette]
prompt = '#f55c1b'           # orange
secondary = '#a90000'        # red
secondary-accent = '#a17a00' # yellow

# [transient_prompt]
#   template = '<p:teal,transparent></><p:on_teal,p:teal>   </><p:teal,transparent></> '
#   foreground = 'p:teal'
#   background = 'transparent'
#   newline = true

[secondary_prompt]
template = '<p:secondary,transparent></><,p:secondary-accent> > </><p:secondary-accent,transparent></> '
foreground = 'p:secondary'
background = 'transparent'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = false

# using shell function set_poshcontext()
[[blocks.segments]]
type = 'text'
style = 'plain'
background = 'transparent'
foreground = 'p:prompt'
template = '{{ if .Env.SHLVL_RELATIVE }}{{ repeat (.Env.SHLVL_RELATIVE | int) "❯" }}{{ else }}{{ repeat .SHLVL "❯" }}{{ end }}'
