#!/usr/bin/env zsh
# [MISE] description="Brew remove (w/ autoremove, cleanup)"
# [MISE] dir="{{cwd}}"

# brew remove (w/ autoremove, cleanup)

print "brew remove /w autoremove and cleanup"
print
brew remove $@
brew autoremove
brew cleanup
mise run pkgmgr:versions
