#!/usr/bin/env zsh
# [MISE] description="Brew tree (deps)"
# [MISE] dir="{{cwd}}"

# brew tree (casks and formulas)

autoload -U colors && colors
CYAN=${fg[cyan]}
MAGENTA=${fg[magenta]}
NORMAL=${fg[default]}

print "brew tree $@"
print
print "${MAGENTA}FORMULAS"
print -- "--------${CYAN}"
if [ -n "$@" ]; then
  brew deps --tree --formula $@
else
  brew leaves | xargs brew deps --tree --formula
fi
print "${NORMAL}"
