#!/usr/bin/env bash
# [MISE] description="Python package for pypi"
# [MISE] dir="{{cwd}}"
eval "$(mise env -C "$HOME/Software/DevBox/util/python")"
exec "$HOME/Software/DevBox/util/python/uv-package" "$@"
