# espanso snippets file - yaml indent is 2 spaces
# https://espanso.org/docs/

matches:
  # Simple text replacement
  - trigger: ":tag"
    replace: |
      ---
      tags: 
      ---

  # Dynamic replacement
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
