#!/usr/bin/env zsh
# [MISE] description="outdated packages"
# [MISE] dir="{{cwd}}"

# homebrew + ports + mise + rustup

GREEN=${fg[green]}
BLUE=${fg[blue]}
NORMAL=${fg[default]}

autoload -U colors && colors
print
print "$GREEN BREW: mac apps, binaries"
print -- "------------------------${fg[blue]}"
brew outdated --greedy --verbose
print
print "${CYAN}MISE: uv, bun, go, node, python, git"
print -- "------------------------------------${BLUE}"
mise outdated --bump --silent
# rustup check
# uv tool upgrade --all
# cargo install-update -a
# -bun -g update
# -gup update
print "${NORMAL}"
