#!/bin/zsh
# Catppuccin Mocha color palette for carapace

# Primary colors
CATPPUCCIN_ROSEWATER="#f5e0dc"
CATPPUCCIN_FLAMINGO="#f2cdcd"
CATPPUCCIN_PINK="#f5c2e7"
CATPPUCCIN_MAUVE="#cba6f7"
CATPPUCCIN_RED="#f38ba8"
CATPPUCCIN_MAROON="#eba0ac"
CATPPUCCIN_PEACH="#fab387"
CATPPUCCIN_YELLOW="#f9e2af"
CATPPUCCIN_GREEN="#a6e3a1"
CATPPUCCIN_TEAL="#94e2d5"
CATPPUCCIN_SKY="#89dceb"
CATPPUCCIN_SAPPHIRE="#74c7ec"
CATPPUCCIN_BLUE="#89b4fa"
CATPPUCCIN_LAVENDER="#b4befe"

# Neutral tones
CATPPUCCIN_TEXT="#cdd6f4"
CATPPUCCIN_SUBTEXT1="#bac2de"
CATPPUCCIN_SUBTEXT0="#a6adc8"
CATPPUCCIN_OVERLAY2="#9399b2"
CATPPUCCIN_OVERLAY1="#7f849c"
CATPPUCCIN_OVERLAY0="#6c7086"
CATPPUCCIN_SURFACE2="#585b70"
CATPPUCCIN_SURFACE1="#45475a"
CATPPUCCIN_SURFACE0="#313244"
CATPPUCCIN_BASE="#1e1e2e"
CATPPUCCIN_MANTLE="#181825"
CATPPUCCIN_CRUST="#11111b"

# Apply carapace styles using variables
carapace --style "carapace.Value=$CATPPUCCIN_BLUE"
carapace --style "carapace.Description=$CATPPUCCIN_SUBTEXT0"
carapace --style "carapace.FlagArg=$CATPPUCCIN_YELLOW"
carapace --style "carapace.FlagNoArg=$CATPPUCCIN_GREEN"
carapace --style "carapace.FlagOptArg=$CATPPUCCIN_PEACH"
carapace --style "carapace.Highlight=bold $CATPPUCCIN_MAUVE underlined"
